// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as Web_window from "bucklescript-tea/src-ocaml/web_window.js";

var $$default = Web_window.$$setTimeout((function (param) {
        Main.main(document.getElementById("app"), undefined);
        
      }), 1.0);

export {
  $$default ,
  $$default as default,
  
}
/* default Not a pure module */
